//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campania
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdPresentacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Vigente { get; set; }
    
        public virtual Presentacion Presentacion { get; set; }
    }
}
