//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farmacia
    {
        public Farmacia()
        {
            this.Llamada_Farmacia = new HashSet<Llamada_Farmacia>();
        }
    
        public int Id { get; set; }
        public string Ruc { get; set; }
        public string Nombre { get; set; }
        public string Localidad { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Propietario { get; set; }
        public string EncargadoCompra { get; set; }
    
        public virtual ICollection<Llamada_Farmacia> Llamada_Farmacia { get; set; }
    }
}
