//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Llamada
    {
        public Llamada()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdFarmacia { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Farmacia Farmacia { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
