//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Llamada_Farmacia
    {
        public Llamada_Farmacia()
        {
            this.Llamada_Farmacia1 = new HashSet<Llamada_Farmacia>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdFarmacia { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> IdLlamadaPadre { get; set; }
        public Nullable<System.DateTime> FechaSigLlamada { get; set; }
    
        public virtual Farmacia Farmacia { get; set; }
        public virtual ICollection<Llamada_Farmacia> Llamada_Farmacia1 { get; set; }
        public virtual Llamada_Farmacia Llamada_Farmacia2 { get; set; }
    }
}
