//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presentacion_Pedido
    {
        public int IdPresentacion { get; set; }
        public int IdPedido { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int Id { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Presentacion Presentacion { get; set; }
    }
}
