//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Pedido = new HashSet<Pedido>();
            this.Farmacia = new HashSet<Farmacia>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Mail { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ICollection<Farmacia> Farmacia { get; set; }
    }
}
