// <auto-generated />
namespace VentasApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class VentasAppBD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VentasAppBD));
        
        string IMigrationMetadata.Id
        {
            get { return "201303072030057_VentasAppBD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
